name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=your_project_key -Dsonar.host.url=https://your-sonarqube-instance -Dsonar.login=$SONAR_TOKEN

  veracode-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload artifact to Veracode
        env:
          VERACODE_API_ID: ${{ secrets.VERACODE_API_ID }}
          VERACODE_API_KEY: ${{ secrets.VERACODE_API_KEY }}
        run: |
          curl -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip pipeline-scan-LATEST.zip
          java -jar pipeline-scan.jar \
            -vid $VERACODE_API_ID \
            -vkey $VERACODE_API_KEY \
            -f target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: veracode-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --region your-region --name your-cluster-name

      - name: Deploy to EKS using ArgoCD
        run: |
          argocd login your-argocd-server --username your-username --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync your-app-name